import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
  import { ToastContainer, toast } from "react-toastify";
  import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer";

const montseratt = Montserrat({ subsets: ["latin"], display:'swap' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montseratt.className}>
        <Navbar />
        <ToastContainer />
        {children}
        <Footer />
        </body>
    </html>
  );
}
